{{- if .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.passwordSecretName | default (printf "%s-postgres-credentials" (include "multigres.fullname" .)) }}
  labels:
    {{- include "multigres.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgres.passwordSecretKey }}: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
